version: '3'
services:
  eway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WEB_ENV: "build:dev"
    container_name: eway
    ports:
      - 9000:9001 # 宿主机可以用 127.0.0.1:9000
