version: '3'
services:
  admin-fe2:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin-fe2 # 引用官网 nginx 镜像
    container_name: admin-fe2
    ports:
      - 8086:80 # 宿主机可以用 127.0.0.1:8085 即可连接容器中的数据库
